framework:
    default_locale: '%default_locale%'
    enabled_locales: ['en', 'fr']
    set_content_language_from_locale: true
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
        providers:
