twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        locales: '%app.locales%'
        upload_directory: '%upload_directory%'
        timezone: '%timezone%'
    paths:
        '%kernel.project_dir%/assets/images': images

when@test:
    twig:
        strict_variables: true
