vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
       icons:
           uri_prefix: /images/icons
           upload_destination: '%kernel.project_dir%/public/images/icons'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
